# Generated by Django 4.0.4 on 2022-05-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choices_choice'),
    ]

    # https://stackoverflow.com/questions/57505839/why-am-i-getting-this-unexpected-keyword-argument-typeerror
    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pud_date',
            new_name='pub_date',
        ),
    ]
